### PR TITLE
Bump xDebug version to 3.0.0

### PR DESCRIPTION
**Pull request by flow-control**
xDebug `3.0.0` has been finally release today
https://xdebug.org/announcements/2020-11-25

This PR updates the PHP `Dockerfile` to use xDebug `3.0.0` and also the configuration file to the new config options.

### CODE REVIEW

**Review by PirxDanford — APPROVED** [review]
Looks good

**Comment by Sieg** [comment]
Hey @flow-control, @PirxDanford but earlier we had the PECL_DEPendencies parameter that could be extended with other stuff you could need, and now you dont? Its not needed anymore? :)

**Comment by flow-control** [comment]
@Sieg you are right, I will change this back to the way it was before

**Comment by AlfonsMartin** [comment]
Changes did not cause problems with xdebug and vscode - phpdebug update did. So please restore PECL_DEPendencies variable then i can merge

**Comment by flow-control** [comment]
@Sieg @AlfonsMartin @PirxDanford fixed this to use `PECL_DEPS' variable again

**Pull request merged**
